---
#
# Ansible managed
#
repository:
  description: Munin monitoring server for RedHat/CentOS or Debian/Ubuntu.
  homepage: https://buluma.github.io/
  topics: monitoring, system, munin, ansible, molecule, tox, playbook, hacktoberfest
